com:
    cxl:
        description: springBoot学习
        title: springBoot
logging:
    level:
        com:
            cxl:
                springBootCrm:
                    controller:
                        TestController: DEBUG
    path: /cxl/local/log
spring:
    banner:
        charset: UTF-8
    datasource:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        jdbc-url: jdbc:oracle:thin:@10.2.201.238:1521:dms
        password: oracle
        username: dms
    jpa:
        database: oracle
        format-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.OracleDialect
                hbm2ddl:
                    auto: none
        show-sql: true
